/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.entities.Produto;
import model.service.ProdutoService;

/**
 *
 * @author jhona
 */
public class CadastroPao extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroPao
     */
    public CadastroPao() {
        initComponents();
        inicializaComboBox();
    }
    
    private void inicializaComboBox(){
        ProdutoService servico = new ProdutoService();
        
        for( Produto p: servico.listarTodos()){
            ///System.out.println("QUANTIDADE: " +p.getQuantidade());
            //System.out.println("NOME:" +p);
            boxProdutos.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcaoCargo = new javax.swing.ButtonGroup();
        PainelCadFun = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        cmpCod = new javax.swing.JTextField();
        cargo = new javax.swing.JLabel();
        opcGerente = new javax.swing.JRadioButton();
        opcAtendente = new javax.swing.JRadioButton();
        opcChefeEstq = new javax.swing.JRadioButton();
        PainelCadProd = new javax.swing.JPanel();
        produto = new javax.swing.JLabel();
        boxProdutos = new javax.swing.JComboBox<>();
        quantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lote = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        botaoAddEstq = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setOpaque(true);

        PainelCadFun.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionário Responsável pelo Cadastro"));
        PainelCadFun.setName(""); // NOI18N

        codigo.setText("Código");

        nome.setText("Nome");

        cmpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNomeActionPerformed(evt);
            }
        });

        cargo.setText("Cargo");

        opcaoCargo.add(opcGerente);
        opcGerente.setText("Gerente");

        opcaoCargo.add(opcAtendente);
        opcAtendente.setText("Atendente");

        opcaoCargo.add(opcChefeEstq);
        opcChefeEstq.setText("Chefe de Estoque");

        javax.swing.GroupLayout PainelCadFunLayout = new javax.swing.GroupLayout(PainelCadFun);
        PainelCadFun.setLayout(PainelCadFunLayout);
        PainelCadFunLayout.setHorizontalGroup(
            PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadFunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadFunLayout.createSequentialGroup()
                        .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadFunLayout.createSequentialGroup()
                                .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelCadFunLayout.createSequentialGroup()
                                .addComponent(opcGerente)
                                .addGap(32, 32, 32)
                                .addComponent(opcAtendente)
                                .addGap(30, 30, 30)
                                .addComponent(opcChefeEstq)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PainelCadFunLayout.createSequentialGroup()
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpCod, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PainelCadFunLayout.setVerticalGroup(
            PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadFunLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargo)
                    .addComponent(opcGerente)
                    .addComponent(opcAtendente)
                    .addComponent(opcChefeEstq))
                .addGap(18, 18, 18))
        );

        opcGerente.getAccessibleContext().setAccessibleDescription("");

        PainelCadProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));
        PainelCadProd.setToolTipText("Cadastro de Produto");

        produto.setText("Produto");

        quantidade.setText("Quantidade");

        txtQuantidade.setBackground(new java.awt.Color(255, 255, 204));

        lote.setText("Lote");

        txtLote.setBackground(new java.awt.Color(255, 255, 204));
        txtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoteActionPerformed(evt);
            }
        });

        botaoAddEstq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-movimento-de-estoque-20.png"))); // NOI18N
        botaoAddEstq.setText("Adicionar ao Estoque");
        botaoAddEstq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddEstqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadProdLayout = new javax.swing.GroupLayout(PainelCadProd);
        PainelCadProd.setLayout(PainelCadProdLayout);
        PainelCadProdLayout.setHorizontalGroup(
            PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadProdLayout.createSequentialGroup()
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lote, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelCadProdLayout.createSequentialGroup()
                .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadProdLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoAddEstq)
                .addGap(18, 18, 18))
        );
        PainelCadProdLayout.setVerticalGroup(
            PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadProdLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produto)
                    .addComponent(boxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lote)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(botaoAddEstq)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCadProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelCadFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelCadProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void cmpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNomeActionPerformed

    private void botaoAddEstqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddEstqActionPerformed
        SimpleDateFormat formatacao = new SimpleDateFormat("dd/MM/yyyy");
        ProdutoService servico = new ProdutoService();
        
        //Produto produto = new Produto();
        Produto produtoSelecionado = (Produto) boxProdutos.getSelectedItem();
        
        produtoSelecionado.QuantidadeAdd(Integer.parseInt(txtQuantidade.getText()));
        produtoSelecionado.setLote(String.valueOf(txtLote.getText()));
        
        servico.AtualizarEstoque(produtoSelecionado);
        
       /* produto.QuantidadeAdd(txtQuantidade.getText() == null ? produtoSelecionado.getQuantidade() : Integer.parseInt(txtQuantidade.getText()));
        produto.setPreco(Double.parseDouble(txtPreco.getText()));
        produto.setLote(String.valueOf(txtLote.getText()));
        try {
            produto.setValidade(formatacao.parse(txtValidade.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(CadastroPao.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("ERRO 1");
        }*/
        
        System.out.println("Nome: " + produtoSelecionado.getNome());
        System.out.println("Quantidade: " + produtoSelecionado.getQuantidade());
        System.out.println("Valor: " + produtoSelecionado.getPreco());
        System.out.println("LOTE: " +produtoSelecionado.getLote());
        System.out.println("Validade: " + formatacao.format(produtoSelecionado.getValidade()));

        
       
    }//GEN-LAST:event_botaoAddEstqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCadFun;
    private javax.swing.JPanel PainelCadProd;
    private javax.swing.JToggleButton botaoAddEstq;
    private javax.swing.JComboBox<Object> boxProdutos;
    private javax.swing.JLabel cargo;
    private javax.swing.JTextField cmpCod;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel lote;
    private javax.swing.JLabel nome;
    private javax.swing.JRadioButton opcAtendente;
    private javax.swing.JRadioButton opcChefeEstq;
    private javax.swing.JRadioButton opcGerente;
    private javax.swing.ButtonGroup opcaoCargo;
    private javax.swing.JLabel produto;
    private javax.swing.JLabel quantidade;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
