/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author jhona
 */
public class CadastroPao extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroPao
     */
    public CadastroPao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcaoCargo = new javax.swing.ButtonGroup();
        PainelCadFun = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        cmpCod = new javax.swing.JTextField();
        cargo = new javax.swing.JLabel();
        opcGerente = new javax.swing.JRadioButton();
        opcAtendente = new javax.swing.JRadioButton();
        opcChefeEstq = new javax.swing.JRadioButton();
        PainelCadProd = new javax.swing.JPanel();
        produto = new javax.swing.JLabel();
        boxProdutos = new javax.swing.JComboBox<>();
        quantidade = new javax.swing.JLabel();
        cmpQtd = new javax.swing.JTextField();
        preco = new javax.swing.JLabel();
        txf_Preco = new javax.swing.JTextField();
        lote = new javax.swing.JLabel();
        cmpLote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        validade = new javax.swing.JFormattedTextField();
        botaoAddEstq = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setOpaque(true);

        PainelCadFun.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionário Responsável pelo Cadastro"));
        PainelCadFun.setName(""); // NOI18N

        codigo.setText("Código");

        nome.setText("Nome");

        cmpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNomeActionPerformed(evt);
            }
        });

        cargo.setText("Cargo");

        opcaoCargo.add(opcGerente);
        opcGerente.setText("Gerente");

        opcaoCargo.add(opcAtendente);
        opcAtendente.setText("Atendente");

        opcaoCargo.add(opcChefeEstq);
        opcChefeEstq.setText("Chefe de Estoque");

        javax.swing.GroupLayout PainelCadFunLayout = new javax.swing.GroupLayout(PainelCadFun);
        PainelCadFun.setLayout(PainelCadFunLayout);
        PainelCadFunLayout.setHorizontalGroup(
            PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadFunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadFunLayout.createSequentialGroup()
                        .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadFunLayout.createSequentialGroup()
                                .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelCadFunLayout.createSequentialGroup()
                                .addComponent(opcGerente)
                                .addGap(32, 32, 32)
                                .addComponent(opcAtendente)
                                .addGap(30, 30, 30)
                                .addComponent(opcChefeEstq)
                                .addContainerGap(39, Short.MAX_VALUE))))
                    .addGroup(PainelCadFunLayout.createSequentialGroup()
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpCod, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PainelCadFunLayout.setVerticalGroup(
            PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadFunLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(PainelCadFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargo)
                    .addComponent(opcGerente)
                    .addComponent(opcAtendente)
                    .addComponent(opcChefeEstq))
                .addGap(18, 18, 18))
        );

        opcGerente.getAccessibleContext().setAccessibleDescription("");

        PainelCadProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));
        PainelCadProd.setToolTipText("Cadastro de Produto");

        produto.setText("Produto");

        boxProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pão Francês", "Pão Doce", "Rosquinha", "Bolo", "Salgados" }));

        quantidade.setText("Quantidade");

        cmpQtd.setBackground(new java.awt.Color(255, 255, 204));

        preco.setText("Preço R$");

        txf_Preco.setBackground(new java.awt.Color(255, 255, 204));
        txf_Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_PrecoActionPerformed(evt);
            }
        });

        lote.setText("Lote");

        cmpLote.setBackground(new java.awt.Color(255, 255, 204));
        cmpLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpLoteActionPerformed(evt);
            }
        });

        jLabel5.setText("Validade");

        validade.setBackground(new java.awt.Color(255, 255, 204));
        try {
            validade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoAddEstq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-movimento-de-estoque-20.png"))); // NOI18N
        botaoAddEstq.setText("Adicionar ao Estoque");

        javax.swing.GroupLayout PainelCadProdLayout = new javax.swing.GroupLayout(PainelCadProd);
        PainelCadProd.setLayout(PainelCadProdLayout);
        PainelCadProdLayout.setHorizontalGroup(
            PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadProdLayout.createSequentialGroup()
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadProdLayout.createSequentialGroup()
                        .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelCadProdLayout.createSequentialGroup()
                        .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadProdLayout.createSequentialGroup()
                                .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(PainelCadProdLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(14, 14, 14)))
                        .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_Preco)
                            .addComponent(validade, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))))
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadProdLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAddEstq)
                        .addGap(24, 24, 24))
                    .addGroup(PainelCadProdLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lote, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmpQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmpLote, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelCadProdLayout.setVerticalGroup(
            PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadProdLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produto)
                    .addComponent(boxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidade)
                    .addComponent(cmpQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lote)
                    .addComponent(cmpLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadProdLayout.createSequentialGroup()
                        .addGroup(PainelCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(validade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadProdLayout.createSequentialGroup()
                        .addComponent(botaoAddEstq)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCadProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelCadFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelCadProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_PrecoActionPerformed

    private void cmpLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpLoteActionPerformed

    private void cmpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCadFun;
    private javax.swing.JPanel PainelCadProd;
    private javax.swing.JToggleButton botaoAddEstq;
    private javax.swing.JComboBox<String> boxProdutos;
    private javax.swing.JLabel cargo;
    private javax.swing.JTextField cmpCod;
    private javax.swing.JTextField cmpLote;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JTextField cmpQtd;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lote;
    private javax.swing.JLabel nome;
    private javax.swing.JRadioButton opcAtendente;
    private javax.swing.JRadioButton opcChefeEstq;
    private javax.swing.JRadioButton opcGerente;
    private javax.swing.ButtonGroup opcaoCargo;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel produto;
    private javax.swing.JLabel quantidade;
    private javax.swing.JTextField txf_Preco;
    private javax.swing.JFormattedTextField validade;
    // End of variables declaration//GEN-END:variables
}
