/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import db.DbException;
import static java.lang.String.valueOf;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.entities.Produto;
import model.service.ProdutoService;

/**
 *
 * @author Edgar
 */
public class Tela_Caixa extends javax.swing.JInternalFrame {
    private static double total = 0;
    SimpleDateFormat formatacao = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form Tela_Caixa
     */
    public Tela_Caixa() {
        initComponents();
        inicializaComboBox();
    }
    
    private void inicializaComboBox(){
        ProdutoService servico = new ProdutoService();
        
        for( Produto p: servico.listarTodos()){

            cmboxProduto.addItem(p);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PainelNotaFiscal = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaNota = new javax.swing.JTable();
        PainelCaixa = new javax.swing.JPanel();
        produto = new javax.swing.JLabel();
        quantidade = new javax.swing.JLabel();
        preco = new javax.swing.JLabel();
        cmboxProduto = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JTextField();
        txtPreco = new javax.swing.JFormattedTextField();
        btnInserir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);

        PainelNotaFiscal.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota Fiscal"));

        tabelaNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço do item", "Quantidade", "Preço total"
            }
        ));
        tabelaNota.setEnabled(false);
        jScrollPane7.setViewportView(tabelaNota);

        javax.swing.GroupLayout PainelNotaFiscalLayout = new javax.swing.GroupLayout(PainelNotaFiscal);
        PainelNotaFiscal.setLayout(PainelNotaFiscalLayout);
        PainelNotaFiscalLayout.setHorizontalGroup(
            PainelNotaFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNotaFiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        PainelNotaFiscalLayout.setVerticalGroup(
            PainelNotaFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNotaFiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        PainelCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa"));

        produto.setText("PRODUTO");

        quantidade.setText("QUANTIDADE");

        preco.setText("PREÇO");

        cmboxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxProdutoActionPerformed(evt);
            }
        });

        txtPreco.setEditable(false);

        btnInserir.setText("Inserir Produto");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Selecione o produto e a quantidade desejada pelo cliente");

        javax.swing.GroupLayout PainelCaixaLayout = new javax.swing.GroupLayout(PainelCaixa);
        PainelCaixa.setLayout(PainelCaixaLayout);
        PainelCaixaLayout.setHorizontalGroup(
            PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCaixaLayout.createSequentialGroup()
                        .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInserir)
                            .addGroup(PainelCaixaLayout.createSequentialGroup()
                                .addComponent(cmboxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelCaixaLayout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelCaixaLayout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(266, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCaixaLayout.createSequentialGroup()
                        .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159))))
        );
        PainelCaixaLayout.setVerticalGroup(
            PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCaixaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidade)
                    .addComponent(preco))
                .addGap(1, 1, 1)
                .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInserir)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("VALOR TOTAL");

        txtValorTotal.setEditable(false);
        txtValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelNotaFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValorTotal)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        
        Produto produtoSelecionado = (Produto) cmboxProduto.getSelectedItem();
        
        try{
            
        System.out.println("QTD: " +txtQuantidade.getText());
        System.out.println("PRECO: " +  txtPreco.getText());
        
            if(txtQuantidade.getText() == null || txtQuantidade.getText().trim().equals("") && txtPreco.getText() == null || txtPreco.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Não há produto Selecionado", "Selecione um Produto", JOptionPane.INFORMATION_MESSAGE);

            }else{
                
                if(produtoSelecionado.getQuantidade() >= Integer.parseInt(txtQuantidade.getText()) ){
                    
                    produtoSelecionado.QuantidadeRemove(Integer.parseInt(txtQuantidade.getText()));                   
                    
                    ProdutoService servico = new ProdutoService();
                    servico.AtualizarEstoqueVenda(produtoSelecionado);
                    
                    double soma = Double.parseDouble(txtQuantidade.getText()) * Double.parseDouble(txtPreco.getText());
                    DefaultTableModel dtmprodutos = (DefaultTableModel) tabelaNota.getModel();
                    Object[] valores = {cmboxProduto.getSelectedItem().toString(), txtPreco.getText(), txtQuantidade.getText(), soma};

                    dtmprodutos.addRow(valores);
                    
                    total = total + soma;
                    txtValorTotal.setText(valueOf(total));
                    txtQuantidade.setText("");
                    txtPreco.setText("");
                    
                    //System.out.println("CODIGO: " +produtoSelecionado.getCodigo());
                    //System.out.println("Nome: " + produtoSelecionado.getNome());
                    //System.out.println("Quantidade: " + produtoSelecionado.getQuantidade());
                    //System.out.println("Valor: " + produtoSelecionado.getPreco());
                    //System.out.println("LOTE: " +produtoSelecionado.getLote());
                    //System.out.println("Validade: " + formatacao.format(produtoSelecionado.getValidade()));
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Quantidade solicitada superior à quantidade em estoque", "Quantidade Insuficiente", JOptionPane.ERROR_MESSAGE);
                    txtQuantidade.setText("");
                }
            }
   
        }catch(NumberFormatException ex){
            System.out.println("EXECAO CAPTURADA:" +ex.getMessage());
            if(txtQuantidade.getText() == null || txtQuantidade.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Informe a quantidade que deseja adicionar à venda", "Quantidade Não Informada", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("ERRO - quantidade nao informada");
            }else{
                System.out.println("ERRO - quantidade informada nao é o do tipo Inteiro ");
                JOptionPane.showMessageDialog(null, "Informe a Quantidade corretamente", "Entrada para quantidade errada", JOptionPane.INFORMATION_MESSAGE);
                txtQuantidade.setText("");
            }

        }catch(DbException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro ao Atualizar o Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void cmboxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxProdutoActionPerformed
        Produto produtoSelecionado = (Produto) cmboxProduto.getSelectedItem();

        txtPreco.setText(String.valueOf(produtoSelecionado.getPreco()));
         
    }//GEN-LAST:event_cmboxProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCaixa;
    private javax.swing.JPanel PainelNotaFiscal;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<Object> cmboxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel produto;
    private javax.swing.JLabel quantidade;
    private javax.swing.JTable tabelaNota;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
